# Generated by Django 4.2.17 on 2025-07-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profile',
            new_name='customer',
        ),
    ]
